INSERT INTO OAUTH_CLIENT_DETAILS(CLIENT_ID, RESOURCE_IDS, CLIENT_SECRET, SCOPE, AUTHORIZED_GRANT_TYPES, AUTHORITIES, ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY)
	VALUES ('blog-website-read-client', 'resource-server-rest-api',
	/*blog-website-oauth2-read-client-password1234*/'$2a$04$Iy/QcXzrS94CRzGFtz71FO/0VXrd.1y.4ayQ40P6pXUWvUj1CXXCy',
	'read', 'password,authorization_code,refresh_token,implicit', 'USER', 10800, 2592000);

INSERT INTO OAUTH_CLIENT_DETAILS(CLIENT_ID, RESOURCE_IDS, CLIENT_SECRET, SCOPE, AUTHORIZED_GRANT_TYPES, AUTHORITIES, ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY)
	VALUES ('blog-website-read-write-client', 'resource-server-rest-api',
	/*blog-website-oauth2-read-write-client-password1234*/'$2a$04$y7F28V5f190YbOkOzdcLnuGi5w2sa.ll9LiD4CtuN2zPt5BPwaFK2',
	'read,write', 'password,authorization_code,refresh_token,implicit', 'USER', 10800, 2592000);

INSERT INTO USER_(ID, USER_NAME, PASSWORD, ACCOUNT_EXPIRED, ACCOUNT_LOCKED, CREDENTIALS_EXPIRED, ENABLED)
  VALUES (1, 'admin', /*admin1234*/'$2a$08$qvrzQZ7jJ7oy2p/msL4M0.l83Cd0jNsX6AJUitbgRXGzge4j035ha', FALSE, FALSE, FALSE, TRUE);

INSERT INTO AUTHORITY(ID, NAME) VALUES(1,'ROLE_OAUTH_ADMIN');
INSERT INTO AUTHORITY(ID, NAME) VALUES(2,'ROLE_ADMIN_PRODUCT');
INSERT INTO AUTHORITY(ID, NAME) VALUES(3,'ROLE_RESOURCE_ADMIN');

INSERT INTO USERS_AUTHORITIES(USER_ID, AUTHORITY_ID) VALUES (1, 1);